### PR TITLE
Tier Two JWST Community Software Standards

### PR DESCRIPTION
**Pull request by mfixstsci**
https://github.com/spacetelescope/ins-jwst-community-software/#contents

- ~~Software Repository Must Have a Code of Conduct File~~
- ~~Project Must Document Citation Information~~
- ~~Software Must Enforce Language-specific Coding Standards (e.g. PEP8)~~
- ~~Software Must Support Recent Version(s) of Python~~
- ~~Project Must Have or Reference a Documented git Workflow or Contributor's Guide~~
- ~~Software Must Document Modules, Classes, and Functions~~
- ~~Project Have Some Unit and/or Regression Tests~~
- ~~Project Must Document a Release Procedure~~
- ~~Project Must Provide Release Notes~~
- ~~Project Must Have Backup Maintainers~~
- ~~Project Must Utilize Code Review/Approval for New Changes~~
- ~~Project Must Use an Automated Dependency Update Tool~~

### CODE REVIEW

**Comment by joseph-long** [comment]
Hahahaha “don’t worry about rewriting for code style when you port it” they said, “this will only be used internally” they said. Glad someone’s still working on it. Thank you and I’m sorry.

**Comment by mfixstsci** [comment]
P-A-I-N...

**Comment by mfixstsci** [comment]
@brynickson we are getting close to closing/merging this PR. Do you or anyone you working with have a documented release procedure for the tool? From what I am seeing, the travis builds are failing, but the most recent merge was made with the same tests failing. I haven't taken the time to look into the failure but figured I could leave that up to the maintainer/developers of the tool.

**Comment by joseph-long** [comment]
of course I documented the release procedure mees https://github.com/spacetelescope/jwst_coronagraph_visibility/blob/master/docs/development.rst

**Comment by mfixstsci** [comment]
> of course I documented the release procedure mees https://github.com/spacetelescope/jwst_coronagraph_visibility/blob/master/docs/development.rst

Whoops, missed that one :sweat_smile: should've known better.

**Comment by joseph-long** [comment]
I tried to unsubscribe from this thread but @josephoenix is still getting notifications and I can't be bothered to sign in to that account to turn it off... so I'll just keep chiming in (un)helpfully 😄

**Pull request merged**
